### ISSUE TITLE
Argument 'clientId' is required but was not present

### ISSUE THREAD

**Issue by guzily** [Webflow-Examples/oauth-hello-world#1]
I follow the steps of webflow apps get started, but there is a problem in the jump authorization interface

```
{
"statusCode": 500,
"error": "Internal Server Error",
"message": "Argument 'clientId' is required but was not present"
}
```

This is the .env file, I only made changes to the .env file . Sensitive information omitted
```
# You can get your client credentials from your workspace dashboard
WEBFLOW_CLIENT_ID=bb4eb0e2....4be64d
WEBFLOW_SECRET=344d30....063f007792fd

# If testing with Ngrok, get the forwarding url from the session detail window.
SERVER_HOST=https://8549-221-216-117-44.jp.ngrok.io
PORT=6666
```
Can you help me find out what is the reason and how to solve it, thank you very much for your answer

**Comment by KevinAzoulay** [comment]
Did you check that you are on .env and not on .env.example ?

**Comment by KevinAzoulay** [comment]
> I follow the steps of webflow apps get started, but there is a problem in the jump authorization interface
> 
> ```
> {
> "statusCode": 500,
> "error": "Internal Server Error",
> "message": "Argument 'clientId' is required but was not present"
> }
> ```
> 
> This is the .env file, I only made changes to the .env file . Sensitive information omitted
> 
> ```
> # You can get your client credentials from your workspace dashboard
> WEBFLOW_CLIENT_ID=bb4eb0e2....4be64d
> WEBFLOW_SECRET=344d30....063f007792fd
> 
> # If testing with Ngrok, get the forwarding url from the session detail window.
> SERVER_HOST=https://8549-221-216-117-44.jp.ngrok.io
> PORT=6666
> ```
> 
> Can you help me find out what is the reason and how to solve it, thank you very much for your answer


Did you check that you are on .env and not on .env.example ?

**Comment by guzily** [comment]
> > I follow the steps of webflow apps get started, but there is a problem in the jump authorization interface
> > ```
> > {
> > "statusCode": 500,
> > "error": "Internal Server Error",
> > "message": "Argument 'clientId' is required but was not present"
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This is the .env file, I only made changes to the .env file . Sensitive information omitted
> > ```
> > # You can get your client credentials from your workspace dashboard
> > WEBFLOW_CLIENT_ID=bb4eb0e2....4be64d
> > WEBFLOW_SECRET=344d30....063f007792fd
> > 
> > # If testing with Ngrok, get the forwarding url from the session detail window.
> > SERVER_HOST=https://8549-221-216-117-44.jp.ngrok.io
> > PORT=6666
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Can you help me find out what is the reason and how to solve it, thank you very much for your answer
> 
> Did you check that you are on .env and not on .env.example ?

yes，I use .env file   This is my code url :[https://stackblitz.com/edit/node-dwmn9m?file=yarn.lock,.env](https://stackblitz.com/edit/node-dwmn9m?file=yarn.lock,.env)

workspace app details are like this
<img width="751" alt="image" src="https://user-images.githubusercontent.com/74231693/216931270-3007f6b1-85c1-4f60-bec9-276761521bc7.png">
when i visit ngrok and click "Authorize Webflow"
<img width="787" alt="image" src="https://user-images.githubusercontent.com/74231693/216932173-db051489-c554-4d78-b6f1-c3806092853b.png">
it show like this
<img width="610" alt="image" src="https://user-images.githubusercontent.com/74231693/216929208-c897862b-d132-4a3f-afce-377876dbf6bd.png">

Thanks for your answer！

**Comment by KevinAzoulay** [comment]
@guzily, You are using 
```WEBFLOW_CLIENT_ID=bb4eb0e2....4be64d    WEBFLOW_SECRET=344d30....063f007792fd```
as variables in .env, but in the server.js file they are declared as CLIENT_ID and CLIENT_SECRET.

Cheers mate ;)

**Comment by guzily** [comment]
@KevinAzoulay  Thanks a lot.   I replaced `WEBFLOW_CLIENT_ID` with `CLIENT_ID`,   `WEBFLOW_SECRET` with `CLIENT_SECRET`. However, different problem arises after I click the `Authorize Webflow`  button. it goes to `https://undefined/oauth/authorize?response_type=code&client_id=bb4eb0e290777acab003e9beb265bba4253b77d17e6eab742cb417bc934be64d`
Details are as follows:
My chrome browser displays Chinese, so the sticker next to it is an English translation
<img width="1023" alt="image" src="https://user-images.githubusercontent.com/74231693/217128680-7a84afbc-a054-40f4-859e-4da369f355fd.png">
My updated code url is [https://stackblitz.com/edit/node-dwmn9m?file=yarn.lock,.env](https://stackblitz.com/edit/node-dwmn9m?file=yarn.lock,.env)
Is there any error in my code? Thanks a lot for your patience!

**Comment by KevinAzoulay** [comment]
@guzily you are welcome :-)
I have the same issue than you exactly and I opened it 3 days ago. 
I’m not getting what is wrong yet. 
Maybe @johnagan can help us ?

**Comment by johnagan** [comment]
yup! we have a bug in the SDK I’m planning to fix tomorrow. I’ll add a fix here as well.

That said, you shouldn’t be using stackblitz here since your credentials in the `.env` are public.

**Comment by guzily** [comment]
@johnagan Maybe I could remove this webflow apps from workplace and then new another one. Thanks for reminding me !

**Comment by johnagan** [comment]
Looks like the problem is this is using the [wrong version of the SDK](https://github.com/Webflow-Examples/oauth-hello-world/blob/main/package.json#L15). It should be v1.2.2. Fix incoming!
